Proper rollback

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -38,6 +38,7 @@ commands:
     parameters:
       workflow_id:
         type: string
+        default: "${CIRCLE_WORKFLOW_ID:0:7}"
       environment:
         type: string
         default: dev
@@ -52,28 +53,39 @@ commands:
             # aws cloudformation delete-stack --stack-name "udapeople-backend-<< parameters.environment >>-<< parameters.workflow_id >>"
             # aws cloudformation delete-stack --stack-name "udapeople-frontend-<< parameters.environment >>-<< parameters.workflow_id >>"
             aws cloudformation delete-stack --stack-name "udapeople-backend-<< parameters.workflow_id >>"
+
+            BUCKET_NAME="udapeople-<< parameters.workflow_id >>"
+
+            aws s3 rm "s3://${BUCKET_NAME}" --recursive
+            aws s3api delete-bucket --bucket $BUCKET_NAME
             aws cloudformation delete-stack --stack-name "udapeople-frontend-<< parameters.workflow_id >>"
       - notification
 
 
-  # revert-migrations:
-  #   description: Revert the last migration if successfully run in the current workflow.
-  #   parameters:
-  #     # Add parameter here
-  #   steps:
-  #     - run:
-  #         name: Revert migrations
-  #         # Add when this will run
-  #         command: |
-  #           # Curl command here to see if there was a successful migration associated with the workflow id, store result in SUCCESS variable
-  #           SUCCESS = 1
-  #           if(( $SUCCESS==1 ));
-  #           then
-  #           #  cd ~/project/backend
-  #           #  npm install
-  #           #  Add revert code here. You can find this in the Getting Started section.
-  #             exit 1
-  #           fi
+  revert-migrations:
+    description: Revert the last migration if successfully run in the current workflow.
+    parameters:
+      # Add parameter here
+      workflow_id:
+        type: string
+        default: "${CIRCLE_WORKFLOW_ID:0:7}"
+    steps:
+      - run:
+          name: Revert migrations
+          # Add when this will run
+          command: |
+            # Example: Memstash.io
+            # SUCCESS=$(curl -H "token: e52b52de-ee26-41a5-86e8-e8dcc3d995a5" --request GET https://api.memstash.io/values/migration_<< parameters.workflow_id >>)
+            # Example: kvdb.io
+            SUCCESS=$(curl --insecure  https://kvdb.io/Af7hn2aPN5kPEE9mtuorgH/migration_<< parameters.workflow_id >>)
+            # Logic for reverting the database state
+            if (( $SUCCESS == 1 ));
+            then
+            #  Add revert code here. You can find this in the Getting Started section.
+              cd ~/project/backend
+              npm run ci
+              npm run migration:revert
+            fi
 orbs:
   slack: circleci/slack@4.9.3
 
@@ -298,8 +310,8 @@ jobs:
             fi
 
      # Here's where you will add some code to rollback on failure
-      - destroy-environment:
-          workflow_id: ${CIRCLE_WORKFLOW_ID:0:7}
+      - destroy-environment
+      - revert-migrations
 
   deploy-frontend:
     docker:
@@ -380,8 +392,8 @@ jobs:
             ansible-playbook -i inventory.txt deploy-backend.yml
 
       # Here's where you will add some code to rollback on failure
-      - destroy-environment:
-          workflow_id: ${CIRCLE_WORKFLOW_ID:0:7}
+      - destroy-environment
+      - revert-migrations
 
   smoke-test:
     docker:
@@ -417,9 +429,9 @@ jobs:
             echo "${API_URL}"
             if curl "${API_URL}/api/status" | grep "ok"
             then
-                echo "Smoke test passed"
+                echo "Backend smoke test passed" && exit 1
             else
-                echo "Smoke test failed" && exit 1
+                echo "Backend smoke test failed" && exit 1
             fi
       - run:
           name: Frontend smoke test.
@@ -430,13 +442,13 @@ jobs:
             if curl -s ${URL} | grep "Welcome"
             then
                 # Change this to 0 after the job fails
-                echo "Smoke test passed" && exit 1
+                echo "Frontend smoke test passed"
             else
-                echo "Smoke test failed" && exit 1
+                echo "Frontend smoke test failed" && exit 1
             fi
       # Here's where you will add some code to rollback on failure
-      # - destroy-environment:
-      #     workflow_id: ${CIRCLE_WORKFLOW_ID:0:7}
+      - destroy-environment
+      - revert-migrations
 
   cloudfront-update:
     docker:
